<?php

namespace App\Services\SisData\DataTransferObjects;

class SisTermStudentData
{
    public function __construct(
        public readonly string $id,// StudentId-TermCode
        public readonly string $studentId,
        public readonly string $userName, //netId,
        public readonly string $enrolledThisTerm,
        public readonly string $hasGraduated,
        public readonly string $effectiveTermCode,
        public readonly string $effectiveTermDescription,
        public readonly string $levelCode,
        public readonly string $levelDescription,
        public readonly string $lastTermAttendedCode,
        public readonly string $lastTermAttendedDescription,
        public readonly string $expectedGraduationDate,
        public readonly string $expectedGraduationTermCode,
        public readonly string $expectedGraduationTermDescription,
        public readonly string $expectedGraduationAcademicYear,
        public readonly string $classificationCode,
        public readonly string $classificationDescription,
        public readonly string $typeCode,
        public readonly string $typeDescription,
        public readonly string $creditHoursMax,
        public readonly string $creditHoursCurrent,
        public readonly string $creditHoursCompleted,
        public readonly string $gpaLevelHoursEarned,
        public readonly string $gpaLevelHoursAttempted,
        public readonly string $gpaLevelQualityPoints,
        public readonly string $gpaLevelGpa,
        public readonly string $entryTermCode,
        public readonly string $entryTermDescription,
        public readonly string $personId,
        public readonly string $firstName,
        public readonly string $lastName,
        public readonly string $termCode,
        public readonly string $termDescription,
        public readonly string $termStartDate,
        public readonly string $termEndDate,
        public readonly string $isCurrentTerm,
        public readonly string $primaryCollegeCode,
        public readonly string $primaryCollegeDescription,
        public readonly string $primaryMajorCode,
        public readonly string $primaryMajorDescription,
        public readonly string $primaryDegreeCode,
        public readonly string $primaryDegreeDescription,
        public readonly string $primaryProgramCode,
        public readonly string $primaryDepartmentCode,
        public readonly string $primaryDepartmentDescription,
        public readonly string $statusCode,
        public readonly string $statusDescription,
    ) {
    }
    public static function fromArray(array $data): self
    {
        // The API returns data in a nested structure with 'data' array
        $studentData = data_get($data, 'data.0', []); // Get first student from data array

        return new self(
            id: data_get($studentData, 'id') ?? '',
            studentId: data_get($studentData, 'studentId') ?? '',
            userName: data_get($studentData, 'userName') ?? '',
            enrolledThisTerm: data_get($studentData, 'enrolledThisTerm') ?? '',
            hasGraduated: data_get($studentData, 'hasGraduated') ?? '',
            effectiveTermCode: data_get($studentData, 'effectiveTerm.code') ?? '',
            effectiveTermDescription: data_get($studentData, 'effectiveTerm.description') ?? '',
            levelCode: data_get($studentData, 'level.code') ?? '',
            levelDescription: data_get($studentData, 'level.description') ?? '',
            lastTermAttendedCode: data_get($studentData, 'lastTermAttended.code') ?? '',
            lastTermAttendedDescription: data_get($studentData, 'lastTermAttended.description') ?? '',
            expectedGraduationDate: data_get($studentData, 'expectedGraduation.date') ?? '',
            expectedGraduationTermCode: data_get($studentData, 'expectedGraduation.term.code') ?? '',
            expectedGraduationTermDescription: data_get($studentData, 'expectedGraduation.term.description') ?? '',
            expectedGraduationAcademicYear: data_get($studentData, 'expectedGraduation.academicYear') ?? '',
            classificationCode: data_get($studentData, 'classification.code') ?? '',
            classificationDescription: data_get($studentData, 'classification.description') ?? '',
            typeCode: data_get($studentData, 'type.code') ?? '',
            typeDescription: data_get($studentData, 'type.description') ?? '',
            creditHoursMax: (string) (data_get($studentData, 'creditHours.max') ?? ''),
            creditHoursCurrent: (string) (data_get($studentData, 'creditHours.current') ?? ''),
            creditHoursCompleted: (string) (data_get($studentData, 'gpa.level.hoursEarned') ?? ''),
            gpaLevelHoursEarned: (string) (data_get($studentData, 'gpa.level.hoursEarned') ?? ''),
            gpaLevelHoursAttempted: (string) (data_get($studentData, 'gpa.level.hoursAttempted') ?? ''),
            gpaLevelQualityPoints: (string) (data_get($studentData, 'gpa.level.qualityPoints') ?? ''),
            gpaLevelGpa: (string) (data_get($studentData, 'gpa.level.gpa') ?? ''),
            entryTermCode: data_get($studentData, 'entry.term.code') ?? '',
            entryTermDescription: data_get($studentData, 'entry.term.description') ?? '',
            personId: data_get($studentData, 'person.id') ?? '',
            firstName: data_get($studentData, 'name.firstName') ?? '',
            lastName: data_get($studentData, 'name.lastName') ?? '',
            termCode: data_get($studentData, 'term.code') ?? '',
            termDescription: data_get($studentData, 'term.description') ?? '',
            termStartDate: data_get($studentData, 'term.startDate') ?? '',
            termEndDate: data_get($studentData, 'term.endDate') ?? '',
            isCurrentTerm: data_get($studentData, 'term.isCurrentTerm') ?? '',
            primaryCollegeCode: data_get($studentData, 'primary.college.code') ?? '',
            primaryCollegeDescription: data_get($studentData, 'primary.college.description') ?? '',
            primaryMajorCode: data_get($studentData, 'primary.major.code') ?? '',
            primaryMajorDescription: data_get($studentData, 'primary.major.description') ?? '',
            primaryDegreeCode: data_get($studentData, 'primary.degree.code') ?? '',
            primaryDegreeDescription: data_get($studentData, 'primary.degree.description') ?? '',
            primaryProgramCode: data_get($studentData, 'primary.program.code') ?? '',
            primaryDepartmentCode: data_get($studentData, 'primary.department.code') ?? '',
            primaryDepartmentDescription: data_get($studentData, 'primary.department.description') ?? '',
            statusCode: data_get($studentData, 'status.code') ?? '',
            statusDescription: data_get($studentData, 'status.description') ?? '',
        );
    }
}